### ISSUE TITLE
Bug issues

### ISSUE THREAD

**Issue by jbrew30** [trendyminds/isolate#19]
Received this issue when trying to log in to accounts that are associated with the isolate plugin. On Prod it just gives me the Craft  modal window "server error." On local I get this. 

Craft CMS: 3.4.24
isolate: 1.3.1

yii\base\ErrorException: Undefined offset: 0 in /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php:383
Stack trace:
#0 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/jbrewer/...', 383)
#1 /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/services/IsolateService.php(383): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/Users/jbrewer/...', 383, Array)
#2 /Users/jbrewer/Documents/repos/goml-refresh/vendor/trendyminds/isolate/src/Isolate.php(79): trendyminds\isolate\services\IsolateService->verifyIsolatedUserAccess(347, '')
#3 [internal function]: trendyminds\isolate\Isolate->trendyminds\isolate\{closure}(Object(craft\events\RegisterUrlRulesEvent))
#4 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RegisterUrlRulesEvent))
#5 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\UrlMa...', 'registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#6 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(329): yii\base\Component->trigger('registerCpUrlRu...', Object(craft\events\RegisterUrlRulesEvent))
#7 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/UrlManager.php(98): craft\web\UrlManager->_getRules()
#8 [internal function]: craft\web\UrlManager->__construct(Array)
#9 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#10 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\UrlMa...', Array, Array)
#11 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\UrlMa...', Array, Array)
#12 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#13 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('urlManager', true)
#14 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->get('urlManager', true)
#15 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(571): craft\web\Application->get('urlManager')
#16 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Request.php(1032): yii\base\Application->getUrlManager()
#17 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/web/Application.php(82): craft\web\Request->resolve()
#18 /Users/jbrewer/Documents/repos/goml-refresh/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/jbrewer/Documents/repos/goml-refresh/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/jbrewer/Documents/repos/goml-refresh/web/index.php(21): yii\base\Application->run()
#21 /Users/jbrewer/.composer/vendor/laravel/valet/server.php(158): require('/Users/jbrewer/...')
#22 {main}

**Comment by jbrew30** [comment]
I uninstall the Default Dashboard plugin and it seems to have fixed it.
